[project]
name = "ross"
version = "0.1.0"
description = "Reactive Optimized Soot Sprites"
authors = [
    {name = "Jaeho Cho",email = "jaeho2025@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib (>=3.10.3,<4.0.0)",
    "scipy (>=1.15.3,<2.0.0)",
    "numpy (>=2.3.0,<3.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
